### PR TITLE
1.3.0+1.19.2

### PR DESCRIPTION
**Pull request by ChrysanthCow**

### CODE REVIEW

**Comment by itsmiir** [comment]
i think your fork is outdated; there's quite a few conflicts

**Comment by ChrysanthCow** [comment]
> i think your fork is outdated; there's quite a few conflicts

Not quite as I actually built off 1.19.3's branch, and backported from there because I think that it was a rewrite.

**Comment by ChrysanthCow** [comment]
There's probably been some commits though, I'll fetch upstream.

**Comment by ChrysanthCow** [comment]
There's a bit of a critical bug in this backport from testing that a friend found, I'll get to fixing it in a tad.

**Comment by itsmiir** [comment]
what was the bug?

**Comment by ChrysanthCow** [comment]
~~It's probably just on my end but I forgot to nullcheck playerList somewhere.~~
It might be a mod interaction on the other end.

**Comment by ChrysanthCow** [comment]
Don't merge yet, as I'm awaiting a crashlog from my friend.

**Comment by ChrysanthCow** [comment]
Sorry, but i no longer have interest in upkeeping this PR.

**Pull request closed without merging**
